#!/bin/sh

mkdir -p -- "./input"
mkdir -p -- "./logs"
mkdir -p -- "./output/obfuscated"
mkdir -p -- "./output/obfuscated/jscrambler"
mkdir -p -- "./output/obfuscated/defendjs"
mkdir -p -- "./output/obfuscated/jsfuck"
mkdir -p -- "./output/obfuscated/javascript2img"
mkdir -p -- "./output/obfuscated/daftLogic"
mkdir -p -- "./output/obfuscated/javascript-obfuscator"
mkdir -p -- "./output/obfuscated/jfogs"
mkdir -p -- "./output/obfuscated/js-obfuscator"
mkdir -p -- "./output/obfuscated/node-obf"
mkdir -p -- "./output/obfuscated/jsobfu"
mkdir -p -- "./output/minified"
mkdir -p -- "./output/minified/babel-minify"
mkdir -p -- "./output/minified/google-closure-compiler"
mkdir -p -- "./output/minified/terser"
mkdir -p -- "./output/minified/uglify"
mkdir -p -- "./output/minified/yuicompressor"